#!/bin/bash
Help()
{
	echo "This program makes a wordlist with all possible words of the specified site"
	echo
	echo "Usage: wordlistmaker <url> <output>"
	echo "Output will be saved in ~/.wordlistmaker"
	echo
	echo "Options:"
	echo "-h	Display this help"
}

Error()
{
        echo "Unknown Option. Type -h to display the help page."
}

no_args="true"
while getopts ":h" option; do
        case $option in
                h)
                        Help
                        exit;;
                \?)
                        Error
                        exit;;
        esac
        no_args="false"
done

[[ "$no_args" == "true" ]] && { Error; exit 1; }

dir=~/.wordlistmaker
wlp=$dir/$2

	if test -d "$dir"; then
		:
	else
		mkdir ~/.wordlistmaker/
	fi

echo "Wordlistmaker by MathSabo"

curl -s $1 | sed 's/[^a-zA-Z ]/ /g' | tr 'A-Z ' 'a-z\n' | grep '[a-z]' | sort -u > $wlp

echo -e "\nFile saved in "$wlp
